[tool.poetry]
name = "flip-take-home"
version = "0.1.0"
description = "Flip Take Home"
authors = ["Jack Kolb <JacksonKolb94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
